[build]
  command = "hugo mod get -u && hugo --gc --minify -b $URL"
  publish = "public"

[build.environment]
  NODE_ENV = "production"
  GO_VERSION = "1.19"
  TZ = "UTC"  # Set to preferred timezone

[context.production.environment]
  HUGO_VERSION = "0.101.0"
  HUGO_ENV = "production"
  
[context.deploy-preview.environment]
  HUGO_VERSION = "0.120.4"

[[redirects]]
from = "/npmjs/*"
to = "/npmjs/"
status = 200
